---
- name: build Lotus daemon
  shell: make lotus
  args:
    chdir: "{{ ansible_env.HOME }}/lotus"
  environment: "{{ lotus_build_env }}"

- name: install Lotus
  become: yes
  shell: make install-daemon
  args:
    chdir: "{{ ansible_env.HOME }}/lotus"

- name: ensure lotus daemon directory exists
  become: true
  file:
    path: "{{ lotus_daemon_path }}"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    state: directory

- name: copy Lotus daemon configuration file
  template:
    src: ../templates/config.toml.j2
    dest: "{{ lotus_daemon_path }}/config.toml"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    mode: "0644"
  vars:
    conf: "{{ lotus_daemon_config }}"

- name: copy Lotus daemon service file
  template:
    src: ../templates/lotus_daemon/lotus-daemon.service.j2
    dest: /etc/systemd/system/lotus-daemon.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - systemd-daemon-reload

- name: enable system service for lotus-daemon
  become: yes
  service:
    name: lotus-daemon
    enabled: yes
    state: started
